name: uget  # the name of the snap
version: "git"  # the version of the snap
summary: easy-to-use download manager  # 79 char long summary
description: |
 Uget (formerly urlgfe) is a simple, lightweight and easy-to-use download
 manager. It provides the following features:
  * Resume downloads.
  * Queue downloads.
  * Classify downloads in categories.
  * Mozilla Firefox integration (through Flashgot plugin).
  * Clipboard monitoring.
  * Import downloads import from HTML files.
  * Batch download.

grade: devel
confinement: strict

apps:
    gtk:
        command: desktop-launch uget-gtk
        plugs: [ home, gsettings, network, network-bind, unity7, x11 ]
parts:
    uget:
        source: http://git.code.sf.net/p/urlget/uget2.git
        plugin: autotools
        after: [ desktop/gtk3 ]
        build-packages:
          - libappindicator3-dev
          - libcurl4-openssl-dev
          - libgstreamer1.0-dev
          - libnotify-dev
          - libssl-dev
        stage-packages:
          - libappindicator3-1
          - libcairo2
          - libcurl3
          - libgstreamer1.0-0
          - libnotify4
          - libpango-1.0-0
          - libpangocairo-1.0-0 
